//fort-awesome
import { library } from '@fortawesome/fontawesome-svg-core';
import {
	faUserSecret,
	faSpinner,
	faPlus,
	faMinus,
	faList,
	faWindowMaximize,
	faXmark,
	faHome,
	faChalkboard,
	faChartBar,
	faRecycle,
	faMagnifyingGlass,
	faAngleLeft,
	faAngleRight,
	faAnglesLeft,
	faAnglesRight,
	faCaretDown,
	faCaretUp,
} from '@fortawesome/free-solid-svg-icons';

library.add(
	faUserSecret,
	faSpinner,
	faPlus,
	faMinus,
	faList,
	faWindowMaximize,
	faXmark,
	faHome,
	faChalkboard,
	faChartBar,
	faRecycle,
	faMagnifyingGlass,
	faAngleLeft,
	faAngleRight,
	faAnglesLeft,
	faAnglesRight,
	faCaretDown,
	faCaretUp,
);
